# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResearchAFN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ResearchAFN

  target 'ResearchAFNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ResearchAFNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

   pod 'AFNetworking', '~> 3.1.0'


end
